# Generated by Django 5.2.4 on 2025-07-14 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='publ_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 14, 11, 23, 27, 624078, tzinfo=datetime.timezone.utc)),
        ),
    ]
