# Generated by Django 5.2.4 on 2025-07-18 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_questions_publ_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='publ_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 18, 20, 18, 23, 269194, tzinfo=datetime.timezone.utc)),
        ),
    ]
